# Use selected_ids to run specific instances (this overrides EVAL_LIMIT random sampling)
selected_ids = [
        "conan-io__conan-10213",
        "conan-io__conan-10812",
        "conan-io__conan-10874",
        "conan-io__conan-10917",
        "conan-io__conan-10959",
        "conan-io__conan-10975",
        "conan-io__conan-11560",
        "conan-io__conan-11655",
        "conan-io__conan-11666",
        "conan-io__conan-12086",
        "conan-io__conan-12307",
        "conan-io__conan-12353",
        "conan-io__conan-12397",
        "conan-io__conan-12762",
        "conan-io__conan-13326",
        "conan-io__conan-13390",
        "conan-io__conan-13450",
        "conan-io__conan-13610",
        "conan-io__conan-13721",
        "conan-io__conan-13757",
        "conan-io__conan-14164",
        "conan-io__conan-14167",
        "conan-io__conan-14177",
        "conan-io__conan-14195",
        "conan-io__conan-14254",
        "conan-io__conan-14296",
        "conan-io__conan-14362",
        "conan-io__conan-14378",
        "conan-io__conan-14616",
        "conan-io__conan-14727",
        "conan-io__conan-14760",
        "conan-io__conan-15007",
        "conan-io__conan-15109",
        "conan-io__conan-15699",
        "conan-io__conan-16038",
        "conan-io__conan-16350",
        "conan-io__conan-8355",
        "conan-io__conan-9099",
        "conan-io__conan-9431",
        "conan-io__conan-9758",
        "python__mypy-10560",
        "python__mypy-10689",
        "python__mypy-11140",
        "python__mypy-11290",
        "python__mypy-11314",
        "python__mypy-11984",
        "python__mypy-13648",
        "python__mypy-14007",
        "python__mypy-14926",
        "python__mypy-15006",
        "python__mypy-15208",
        "python__mypy-15306",
        "python__mypy-15541",
        "python__mypy-15642",
        "python__mypy-15876",
        "python__mypy-16013",
        "python__mypy-16303",
        "python__mypy-16519",
        "python__mypy-16717",
        "python__mypy-16729",
        "python__mypy-16963",
        "python__mypy-17256",
        "python__mypy-5617",
        "python__mypy-9097",
        "python__mypy-9573",
        "python__mypy-9625",
        "python__mypy-9663",
        "python__mypy-9796"
]

# To run more instances, first pull their .sif images using pull_images_on_hpc.sh
# Example: bash evaluation/benchmarks/swe_bench/scripts/pull_images_on_hpc.sh \
#   --dockerhub-user peillin --dataset princeton-nlp/SWE-bench_Verified --slice 0:5
